pipeline:

  build:
    image: openjdk:11-slim
    commands:
      - cd xtraplatform-base 
      - ../gradlew assemble -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_PASS

  publish:
    image: openjdk:11-slim
    commands:
      - cd xtraplatform-base 
      - ../gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_PASS
#    when:
#      event: tag
#      branch: master

  notify:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    secrets: [ slack_webhook ]
