npmScopes:
  xtraplatform:
    npmAuthToken: "${BINTRAY_NPM_TOKEN:-not_set}"
    npmPublishRegistry: "https://api.bintray.com/npm/iide/npm/"
    npmRegistryServer: "https://api.bintray.com/npm/iide/npm/"

packageExtensions:
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@xtraplatform-core@*":
    dependencies:
      babel-loader: "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
  feature-u@*:
    peerDependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
