npmScopes:
  xtraplatform:
    npmPublishRegistry: "https://api.bintray.com/npm/iide/npm/"
    npmRegistryServer: "https://api.bintray.com/npm/iide/npm/"
    npmAuthToken: "${BINTRAY_NPM_TOKEN:-not_set}"

packageExtensions:
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  feature-u@*:
    peerDependencies:
      prop-types: "*"
  "@xtraplatform/core@*":
    dependencies:
      "regenerator-runtime": "*"
      "eslint-plugin-babel": "*"
      "eslint-plugin-import": "*"
      "eslint-plugin-jsx-a11y": "*"
      "eslint-plugin-react": "*"
      "eslint-plugin-react-hooks": "*"
      "eslint-import-resolver-node": "*"
#  promise-inflight@*:
#    peerDependencies:
#      bluebird: "*"
#  node-fetch@*:
#    peerDependencies:
#      encoding: "*"
#  http-proxy@*:
#    dependencies:
#      debug: "*"
#  webpack-dev-server@*:
#    dependencies:
#      supports-color: "*"
#  follow-redirects@*:
#    peerDependencies:
#      debug: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
