packageExtensions:
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@xtraplatform-core@*":
    dependencies:
      babel-loader: "*"
  feature-u@*:
    peerDependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
